### PR TITLE
AOP now cooperates with Annotations ignore section

### PR DESCRIPTION
**Pull request by mrtnzlml**
Not sure if it's good idea, but it's needed if you want to ignore some annotations in presenter for example. Or is there another way how to do that better?

### CODE REVIEW

**Comment by enumag** [comment]
@mrtnzlml I think you missed this: https://github.com/Kdyby/Annotations/blob/master/src/Kdyby/Annotations/DI/AnnotationsExtension.php#L30-L33

**Comment by mrtnzlml** [comment]
No, I don't. It doesn't work with AOP. Try it, it's very funny to figure it out... :))

**Comment by enumag** [comment]
Oh I see. Kdyby/Aop probably reads the annotations compile-time which is why it ignores the configuration from Kdyby/Annotations, right?

Well if you magically read the configuration of Kdyby/Annotations, you can as well remove `AnnotationReader::addGlobalIgnoredName('persistent');` because Kdyby/Annotations has that in ignored annotations.

**Comment by mrtnzlml** [comment]
Well I am not really sure. It looks like it uses one AnnotationReader for Annotations and second for AOP (maybe?). I didn't look into it deeper. It's not possible to remove `@persistent` annotation from this extension. I am reading only `ignore` section from config...

**Comment by enumag** [comment]
So? Persistent is in the default configuration of AnnotationsExtension: https://github.com/Kdyby/Annotations/blob/master/src/Kdyby/Annotations/DI/AnnotationsExtension.php#L31

And yes, you're right that AOP uses different instance of AnnotationReader. I don't see any problem with that though. There are good reasons for it to work this way.

**Comment by mrtnzlml** [comment]
In this implementation it doesn't work (obviously). I will look at it later, should be possible to implement it better... (-:

**Comment by fprochazka** [comment]
Oh I see now. I think we're solving it on the wrong layer. If the AnnotationsExtension should be used with AOP, then the AnnotationsExtension should configure this thing earlier.

**Comment by fprochazka** [comment]
@mrtnzlml co takhle https://github.com/Kdyby/Annotations/commit/2380836b9d950f13be30445a52950d6c9d27863e ? :)

**Comment by mrtnzlml** [comment]
:+1: Thank you!

**Pull request closed without merging**
