### PR TITLE
PhpGenerator: Fixed compatibility with nette/php-generator (leading s…

### PR DESCRIPTION
**Pull request by norbe**
…lashes are removed if ClassType is not attached to PhpNamespace)

### CODE REVIEW

**Comment by jost125** [comment]
+1 without this it is not working on newer nette php generator, therefore the library is not working in nette 2.3. @fprochazka Can you merge it pls?

**Comment by fprochazka** [comment]
@norbe @jost125 thank you guys :)

**Comment by fprochazka** [comment]
@norbe are you still using it? Would you be interested in helping me to maintain it?

**Comment by norbe** [comment]
We are using it in our ecommerce system. I'm not sure if I will have enoguht time, but I can try it..

**Pull request closed without merging**
